name: docker-dev

on:
  workflow_dispatch:

jobs:
  build-docker:
    if: github.repository == 'catlair/BiliTools'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set Docker tag
        run: |
          sed -i 2a\echo\ version=dev docker-entrypoint.sh
          echo $(date)-dev >> src/version.txt
          sed -i s/bilitools:latest/bilitools:dev/ docker/deploy.Dockerfile
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: 'linux/amd64'
          tags: catlair/bilitools:dev
      - name: Build and Push Deploy
        id: docker_build_deploy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/deploy.Dockerfile
          push: true
          platforms: 'linux/amd64'
          tags: catlair/bilitools-deploy:dev
  release:
    needs: build-docker
    if: github.repository == 'catlair/BiliTools'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy dist
        run: |
          docker pull catlair/bilitools:dev
          docker run -id --entrypoint sh --name copy_dist catlair/bilitools:dev
          docker cp copy_dist:/usr/src/app/node_modules .
          docker cp copy_dist:/usr/src/app/dist .
          mv node_modules dist
      - name: ZIP
        run: |
          cd dist
          zip -r -q tencent_scf.zip *
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - name: Install dependencies
        run: |
          rm yarn.lock
          yarn
          npm install -g typescript rollup
      - name: Build
        run: |
          yarn build:rollup
          cp dist/rollup gh-release-dev -r
          cp package.json gh-release-dev
      - name: Commit files to gh-release branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'release: Commit from GitHub Actions (dev)'
          branch: gh-release
          commit_options: '--no-verify --signoff'
          file_pattern: gh-release-dev/**
          push_options: '--force'
          skip_fetch: true
          skip_checkout: true
          create_branch: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/tencent_scf.zip
            gh-release-dev/index.js
            gh-release-dev/cat_bili_ql.js
            gh-release-dev/index.scf.js
            gh-release-dev/index.scf.min.js
            package.json
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
